apiVersion: v1
kind: Service
metadata:
  labels:
    app: luna-ml
  name: luna-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: luna-ml
  sessionAffinity: None
  type: NodePort
