module.exports = {
    FETCH_JUDGE_INVITATION_SUMMARY_FULFILLED: 'FETCH_JUDGE_INVITATION_SUMMARY_FULFILLED',
    FETCH_JUDGE_INVITATION_SUMMARY_REJECTED: 'FETCH_JUDGE_INVITATION_SUMMARY_REJECTED',
    FETCH_JUDGE_INVITATION_SUMMARY_REQUEST: 'FETCH_JUDGE_INVITATION_SUMMARY_REQUEST',
    PUT_JUDGE_INVITATION_FULFILLED: 'PUT_JUDGE_INVITATION_FULFILLED',
    PUT_JUDGE_INVITATION_REJECTED: 'PUT_JUDGE_INVITATION_REJECTED',
    PUT_JUDGE_INVITATION_REQUEST: 'PUT_JUDGE_INVITATION_REQUEST'
};
