module.exports = {
    FETCH_NOTIFICATION_DETAIL_FULFILLED: 'FETCH_NOTIFICATION_DETAIL_FULFILLED',
    FETCH_NOTIFICATION_DETAIL_REJECTED: 'FETCH_NOTIFICATION_DETAIL_REJECTED',
    FETCH_NOTIFICATION_DETAIL_REQUEST: 'FETCH_NOTIFICATION_DETAIL_REQUEST',
    FETCH_NOTIFICATION_DETAIL_FORCED: 'FETCH_NOTIFICATION_DETAIL_FORCED',

    FETCH_NOTIFICATION_FULFILLED: 'FETCH_NOTIFICATION_FULFILLED',
    FETCH_NOTIFICATION_REJECTED: 'FETCH_NOTIFICATION_REJECTED',
    FETCH_NOTIFICATION_REQUEST: 'FETCH_NOTIFICATION_REQUEST',

    FETCH_NOTIFICATION_READ_FULFILLED: 'FETCH_NOTIFICATION_READ_FULFILLED',
    FETCH_NOTIFICATION_READ_REJECTED: 'FETCH_NOTIFICATION_READ_REJECTED',
    FETCH_NOTIFICATION_READ_REQUEST: 'FETCH_NOTIFICATION_READ_REQUEST',

    FETCH_NOTIFICATION_READ_ALL_FULLFILLDED: 'FETCH_NOTIFICATION_READ_ALL_FULLFILLDED',

    FETCH_NOTIFICATION_READ_BY_ID_FULFILLED: 'FETCH_NOTIFICATION_READ_BY_ID_FULFILLED',
    FETCH_NOTIFICATION_READ_BY_ID_REJECTED: 'FETCH_NOTIFICATION_READ_BY_ID_REJECTED',
    FETCH_NOTIFICATION_READ_BY_ID_REQUEST: 'FETCH_NOTIFICATION_READ_BY_ID_REQUEST',
};
