module.exports = {
    FETCH_INREVIEW_OPPORTUNITY_LIST_FULFILLED: 'FETCH_INREVIEW_OPPORTUNITY_LIST_FULFILLED',
    FETCH_INREVIEW_OPPORTUNITY_LIST_REJECTED: 'FETCH_INREVIEW_OPPORTUNITY_LIST_REJECTED',
    FETCH_INREVIEW_OPPORTUNITY_LIST_REQUEST: 'FETCH_INREVIEW_OPPORTUNITY_LIST_REQUEST',

    FETCH_ABOUTTOSTART_OPPORTUNITY_LIST_FULFILLED: 'FETCH_ABOUTTOSTART_OPPORTUNITY_LIST_FULFILLED',
    FETCH_ABOUTTOSTART_OPPORTUNITY_LIST_REJECTED: 'FETCH_ABOUTTOSTART_OPPORTUNITY_LIST_REJECTED',
    FETCH_ABOUTTOSTART_OPPORTUNITY_LIST_REQUEST: 'FETCH_ABOUTTOSTART_OPPORTUNITY_LIST_REQUEST',

    FETCH_CLOSED_OPPORTUNITY_LIST_FULFILLED: 'FETCH_CLOSED_OPPORTUNITY_LIST_FULFILLED',
    FETCH_CLOSED_OPPORTUNITY_LIST_REJECTED: 'FETCH_CLOSED_OPPORTUNITY_LIST_REJECTED',
    FETCH_CLOSED_OPPORTUNITY_LIST_REQUEST: 'FETCH_CLOSED_OPPORTUNITY_LIST_REQUEST',

    FETCH_OPPORTUNITY_SUMMARY_FULFILLED: 'FETCH_OPPORTUNITY_SUMMARY_FULFILLED',
    FETCH_OPPORTUNITY_SUMMARY_REJECTED: 'FETCH_OPPORTUNITY_SUMMARY_REJECTED',
    FETCH_OPPORTUNITY_SUMMARY_REQUEST: 'FETCH_OPPORTUNITY_SUMMARY_REQUEST',

    FETCH_PENDING_OPPORTUNITIES_SUMMARY_FULFILLED: 'FETCH_PENDING_OPPORTUNITIES_SUMMARY_FULFILLED',
    FETCH_PENDING_OPPORTUNITIES_SUMMARY_REJECTED: 'FETCH_PENDING_OPPORTUNITIES_SUMMARY_REJECTED',
    FETCH_PENDING_OPPORTUNITIES_SUMMARY_REQUEST: 'FETCH_PENDING_OPPORTUNITIES_SUMMARY_REQUEST',

    RECRUITER_OPPORTUNITY_LIST_FULFILLED: 'RECRUITER_OPPORTUNITY_LIST_FULFILLED',
    RECRUITER_OPPORTUNITY_LIST_REJECTED: 'RECRUITER_OPPORTUNITY_LIST_REJECTED',
    RECRUITER_OPPORTUNITY_LIST_REQUEST: 'RECRUITER_OPPORTUNITY_LIST_REQUEST',

    RECRUITER_OPPORTUNITY_MATCH_FULFILLED: 'RECRUITER_OPPORTUNITY_MATCH_FULFILLED',
    RECRUITER_OPPORTUNITY_MATCH_REJECTED: 'RECRUITER_OPPORTUNITY_MATCH_REJECTED',
    RECRUITER_OPPORTUNITY_MATCH_REQUEST: 'RECRUITER_OPPORTUNITY_MATCH_REQUEST',

    RECRUITER_OPPORTUNITY_COMPLETE_TAG_LIST_FULFILLED: 'RECRUITER_OPPORTUNITY_COMPLETE_TAG_LIST_FULFILLED',
    RECRUITER_OPPORTUNITY_COMPLETE_TAG_LIST_REJECTED: 'RECRUITER_OPPORTUNITY_COMPLETE_TAG_LIST_REJECTED',
    RECRUITER_OPPORTUNITY_COMPLETE_TAG_LIST_REQUEST: 'RECRUITER_OPPORTUNITY_COMPLETE_TAG_LIST_REQUEST',

    RECRUITER_OPPORTUNITY_CURRENT_TAG_LIST_FULFILLED: 'RECRUITER_OPPORTUNITY_CURRENT_TAG_LIST_FULFILLED',
    RECRUITER_OPPORTUNITY_CURRENT_TAG_LIST_REJECTED: 'RECRUITER_OPPORTUNITY_CURRENT_TAG_LIST_REJECTED',
    RECRUITER_OPPORTUNITY_CURRENT_TAG_LIST_REQUEST: 'RECRUITER_OPPORTUNITY_CURRENT_TAG_LIST_REQUEST',

    RECRUITER_OPPORTUNITY_SAVE_TAGS_FULFILLED: 'RECRUITER_OPPORTUNITY_SAVE_TAGS_FULFILLED',
    RECRUITER_OPPORTUNITY_SAVE_TAGS_REJECTED: 'RECRUITER_OPPORTUNITY_SAVE_TAGS_REJECTED',
    RECRUITER_OPPORTUNITY_SAVE_TAGS_REQUEST: 'RECRUITER_OPPORTUNITY_SAVE_TAGS_REQUEST',

    RECRUITER_OPPORTUNITY_CONFIGURATION_FULFILLED: 'RECRUITER_OPPORTUNITY_CONFIGURATION_FULFILLED',
    RECRUITER_OPPORTUNITY_CONFIGURATION_REJECTED: 'RECRUITER_OPPORTUNITY_CONFIGURATION_REJECTED',
    RECRUITER_OPPORTUNITY_CONFIGURATION_REQUEST: 'RECRUITER_OPPORTUNITY_CONFIGURATION_REQUEST',

    RECRUITER_OPPORTUNITY_CONFIGURATION_BY_ID_FULFILLED: 'RECRUITER_OPPORTUNITY_CONFIGURATION_BY_ID_FULFILLED',
    RECRUITER_OPPORTUNITY_CONFIGURATION_BY_ID_REJECTED: 'RECRUITER_OPPORTUNITY_CONFIGURATION_BY_ID_REJECTED',
    RECRUITER_OPPORTUNITY_CONFIGURATION_BY_ID_REQUEST: 'RECRUITER_OPPORTUNITY_CONFIGURATION_BY_ID_REQUEST',

    RECRUITER_OPPORTUNITY_SAVE_EXPERT_CONFIGURATION_FULFILLED: 'RECRUITER_OPPORTUNITY_SAVE_EXPERT_CONFIGURATION_FULFILLED',
    RECRUITER_OPPORTUNITY_SAVE_EXPERT_CONFIGURATION_REJECTED: 'RECRUITER_OPPORTUNITY_SAVE_EXPERT_CONFIGURATION_REJECTED',
    RECRUITER_OPPORTUNITY_SAVE_EXPERT_CONFIGURATION_REQUEST: 'RECRUITER_OPPORTUNITY_SAVE_EXPERT_CONFIGURATION_REQUEST',

    RECRUITER_OPPORTUNITY_SAVE_CHALLENGE_CONFIGURATION_FULFILLED: 'RECRUITER_OPPORTUNITY_SAVE_CHALLENGE_CONFIGURATION_FULFILLED',
    RECRUITER_OPPORTUNITY_SAVE_CHALLENGE_CONFIGURATION_REJECTED: 'RECRUITER_OPPORTUNITY_SAVE_CHALLENGE_CONFIGURATION_REJECTED',
    RECRUITER_OPPORTUNITY_SAVE_CHALLENGE_CONFIGURATION_REQUEST: 'RECRUITER_OPPORTUNITY_SAVE_CHALLENGE_CONFIGURATION_REQUEST',

    RECRUITER_OPPORTUNITY_CREATE_CHALLENGE_FULFILLED: 'RECRUITER_OPPORTUNITY_CREATE_CHALLENGE_FULFILLED',
    RECRUITER_OPPORTUNITY_CREATE_CHALLENGE_REJECTED: 'RECRUITER_OPPORTUNITY_CREATE_CHALLENGE_REJECTED',
    RECRUITER_OPPORTUNITY_CREATE_CHALLENGE_REQUEST: 'RECRUITER_OPPORTUNITY_CREATE_CHALLENGE_REQUEST',
    
    EXPERT_ACCEPT_PENDING_OPPORTUNITY_FULFILLED: 'EXPERT_ACCEPT_PENDING_OPPORTUNITY_FULFILLED',
    EXPERT_ACCEPT_PENDING_OPPORTUNITY_REJECTED: 'EXPERT_ACCEPT_PENDING_OPPORTUNITY_REJECTED',
    EXPERT_ACCEPT_PENDING_OPPORTUNITY_REQUEST: 'EXPERT_ACCEPT_PENDING_OPPORTUNITY_REQUEST',

    EXPERT_DECLINE_PENDING_OPPORTUNITY_FULFILLED: 'EXPERT_DECLINE_PENDING_OPPORTUNITY_FULFILLED',
    EXPERT_DECLINE_PENDING_OPPORTUNITY_REJECTED: 'EXPERT_DECLINE_PENDING_OPPORTUNITY_REJECTED',
    EXPERT_DECLINE_PENDING_OPPORTUNITY_REQUEST: 'EXPERT_DECLINE_PENDING_OPPORTUNITY_REQUEST',

    RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_FULFILLED: 'RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_FULFILLED',
    RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_REJECTED: 'RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_REJECTED',
    RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_REQUEST: 'RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_REQUEST',
    RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_RESET: 'RECRUITER_OPPORTUNITY_FETCH_CHALLENGE_RESET',

    RESET_EXPERT_OPPORTUNITY_LIST : 'RESET_EXPERT_OPPORTUNITY_LIST',

    EXPERT_OPPORTUNITY_LIST_FULFILLED:  'EXPERT_OPPORTUNITY_LIST_FULFILLED',
    EXPERT_OPPORTUNITY_LIST_REJECTED:   'EXPERT_OPPORTUNITY_LIST_REJECTED',
    EXPERT_OPPORTUNITY_LIST_REQUEST:    'EXPERT_OPPORTUNITY_LIST_REQUEST',

    EXPERT_OPPORTUNITY_ARCHIVED_LIST_FULFILLED:  'EXPERT_OPPORTUNITY_ARCHIVED_LIST_FULFILLED',
    EXPERT_OPPORTUNITY_ARCHIVED_LIST_REJECTED:   'EXPERT_OPPORTUNITY_ARCHIVED_LIST_REJECTED',
    EXPERT_OPPORTUNITY_ARCHIVED_LIST_REQUEST:    'EXPERT_OPPORTUNITY_ARCHIVED_LIST_REQUEST',

    EXTEND_MATCH_FULFILLED:  'EXTEND_MATCH_FULFILLED',
    EXTEND_MATCH_REJECTED:   'EXTEND_MATCH_REJECTED',
    EXTEND_MATCH_REQUEST:    'EXTEND_MATCH_REQUEST',
};
