module.exports = {
    REVIEW_USER_LIST_FULFILLED: 'REVIEW_USER_LIST_FULFILLED',
    REVIEW_USER_LIST_REJECTED: 'REVIEW_USER_LIST_REJECTED',
    REVIEW_USER_LIST_REQUEST: 'REVIEW_USER_LIST_REQUEST',

    REVIEW_USER_GET_FULFILLED: 'REVIEW_USER_GET_FULFILLED',
    REVIEW_USER_GET_REJECTED: 'REVIEW_USER_GET_REJECTED',
    REVIEW_USER_GET_REQUEST: 'REVIEW_USER_GET_REQUEST',

    REVIEW_USER_POST_FULFILLED: 'REVIEW_USER_POST_FULFILLED',
    REVIEW_USER_POST_REJECTED: 'REVIEW_USER_POST_REJECTED',
    REVIEW_USER_POST_REQUEST: 'REVIEW_USER_POST_REQUEST',

    REVIEW_OPPORTUNITY_GET_FULFILLED: 'REVIEW_OPPORTUNITY_GET_FULFILLED',
    REVIEW_OPPORTUNITY_GET_REJECTED: 'REVIEW_OPPORTUNITY_GET_REJECTED',
    REVIEW_OPPORTUNITY_GET_REQUEST: 'REVIEW_OPPORTUNITY_GET_REQUEST',

    LEADERBOARD_FULFILLED: 'LEADERBOARD_FULFILLED',
    LEADERBOARD_REJECTED: 'LEADERBOARD_REJECTED',
    LEADERBOARD_REQUEST: 'LEADERBOARD_REQUEST',

    PLAYER_ANSWER_FULFILLED: 'PLAYER_ANSWER_FULFILLED',
    PLAYER_ANSWER_REJECTED: 'PLAYER_ANSWER_REJECTED',
    PLAYER_ANSWER_REQUEST: 'PLAYER_ANSWER_REQUEST',

};
