module.exports = {
    PROCESS_LIST_GET_FULFILLED: 'PROCESS_LIST_GET_FULFILLED',
    PROCESS_LIST_GET_REJECTED: 'PROCESS_LIST_GET_REJECTED',
    PROCESS_LIST_GET_REQUEST: 'PROCESS_LIST_GET_REQUEST',

};
