module.exports = {
    UPLOAD_IMAGE_FULFILLED: 'UPLOAD_IMAGE_FULFILLED',
    UPLOAD_IMAGE_REJECTED: 'UPLOAD_IMAGE_REJECTED',
    UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',

    UPLOAD_FILE_FULFILLED: 'UPLOAD_FILE_FULFILLED',
    UPLOAD_FILE_REJECTED: 'UPLOAD_FILE_REJECTED',
    UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST'
};