module.exports = {
    FETCH_USER_INFO_FULFILLED: 'FETCH_USER_INFO_FULFILLED',
    FETCH_USER_INFO_REJECTED: 'FETCH_USER_INFO_REJECTED',
    FETCH_USER_INFO_REQUEST: 'FETCH_USER_INFO_REQUEST',
    PUT_USER_INFO_FULFILLED: 'PUT_USER_INFO_FULFILLED',
    PUT_USER_INFO_REJECTED: 'PUT_USER_INFO_REJECTED',
    PUT_USER_INFO_REQUEST: 'PUT_USER_INFO_REQUEST'
};
