version: '3'
services:
    reverseproxy:
        image: eu.gcr.io/devops-tools-228909/fluttr-architecture-image-repository/fluttrproxynginx7:prd
        build: ./reverseproxy/
        ports:
            - "80:80"
            - "443:443"
        restart: always
    reverseproxy_plus:
        image: eu.gcr.io/devops-tools-228909/fluttr-architecture-image-repository/reverseproxyplus:${TAG}
        build: ./reverseproxy_plus/
        ports:
            - "80:80"
            - "443:443"
        restart: always
    frontend:
        image: eu.gcr.io/devops-tools-228909/fluttr-frontend-image-repository/fluttrfrontend:prd
        build: ./frontend/
        ports:
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
        restart: always
    postgres:
        image: mdillon/postgis:9.6
        container_name: postgres
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_DBNAME=bizaround
            - POSTGRES_USER=bizaround
            - POSTGRES_PASS=bizaround
            - POSTGRES_PORT=5432
            - PGDATA=/var/lib/postgresql/data/pgdata #needed for kubernetes or the image will bootloop
        volumes:
            - $PWD/output_files/postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    wildfly:
        image: eu.gcr.io/exalted-entity-163908/fluttr-architecture-image-repository/fluttras1:prd
        container_name: wildfly
        build: ./wildfly/
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=bizaround
            - DB_USER=bizaround
            - DB_PASS=bizaround
            - DS_NAME=postgresDS
            - JNDI_NAME=java:jboss/datasources/postgresDS
            - SPRING_PROFILES_ACTIVE=prd
            - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
            - BIZAROUND_ENVIRONMENT=prod
        ports:
            - 8080:8080
            - 9990:9990
volumes:
    jboss-conf: {}
