apiVersion: v1
kind: Service
metadata:
  labels:
    app: controlroom
  name: controlroom-svc
  namespace: default
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: controlroom
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
