apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controlroom
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controlroom
    spec:
      containers:
        - name: controlroom
          image: giantswarm/dummy-image:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8090
