apiVersion: v1
kind: Service
metadata:
  labels:
    app: slackintegration
  name: slackintegration-svc
  namespace: default
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: slackintegration
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
