export function getCountryPrefix(){
    let numbers = [
        {id:'AC', name : 'AC (+247)'},
        {id:'AF', name : 'Afghanistan (+93)'},
        {id:'AL', name : 'Albania (+355)'},
        {id:'DZ', name : 'Algeria (+213)'},
        {id:'AS', name : 'American Samoa (+1)'},
        {id:'AD', name : 'Andorra (+376)'},
        {id:'AO', name : 'Angola (+244)'},
        {id:'AI', name : 'Anguilla (+1)'},
        {id:'AG', name : 'Antigua and Barbuda (+1)'},
        {id:'AR', name : 'Argentina (+54)'},
        {id:'AM', name : 'Armenia (+374)'},
        {id:'AW', name : 'Aruba (+297)'},
        {id:'AU', name : 'Australia (+61)'},
        {id:'AT', name : 'Austria (+43)'},
        {id:'AZ', name : 'Azerbaijan (+994)'},
        {id:'BS', name : 'Bahamas (+1)'},
        {id:'BH', name : 'Bahrain (+973)'},
        {id:'BD', name : 'Bangladesh (+880)'},
        {id:'BB', name : 'Barbados (+1)'},
        {id:'BY', name : 'Belarus (+375)'},
        {id:'BE', name : 'Belgium (+32)'},
        {id:'BZ', name : 'Belize (+501)'},
        {id:'BJ', name : 'Benin (+229)'},
        {id:'BM', name : 'Bermuda (+1)'},
        {id:'BT', name : 'Bhutan (+975)'},
        {id:'BO', name : 'Bolivia (+591)'},
        {id:'BA', name : 'Bosnia and Herzegovina (+387)'},
        {id:'BW', name : 'Botswana (+267)'},
        {id:'BR', name : 'Brazil (+55)'},
        {id:'IO', name : 'British Indian Ocean Territory (+246)'},
        {id:'VG', name : 'British Virgin Islands (+1)'},
        {id:'BN', name : 'Brunei (+673)'},
        {id:'BG', name : 'Bulgaria (+359)'},
        {id:'BF', name : 'Burkina Faso (+226)'},
        {id:'BI', name : 'Burundi (+257)'},
        {id:'KH', name : 'Cambodia (+855)'},
        {id:'CM', name : 'Cameroon (+237)'},
        {id:'CA', name : 'Canada (+1)'},
        {id:'CV', name : 'Cape Verde (+238)'},
        {id:'KY', name : 'Cayman Islands (+1)'},
        {id:'CF', name : 'Central African Republic (+236)'},
        {id:'TD', name : 'Chad (+235)'},
        {id:'CL', name : 'Chile (+56)'},
        {id:'CN', name : 'China (+86)'},
        {id:'CX', name : 'Christmas Island (+61)'},
        {id:'CC', name : 'Cocos Islands (+61)'},
        {id:'CO', name : 'Colombia (+57)'},
        {id:'KM', name : 'Comoros (+269)'},
        {id:'CG', name : 'Congo (+242)'},
        {id:'CK', name : 'Cook Islands (+682)'},
        {id:'CR', name : 'Costa Rica (+506)'},
        {id:'HR', name : 'Croatia (+385)'},
        {id:'CU', name : 'Cuba (+53)'},
        {id:'CY', name : 'Cyprus (+357)'},
        {id:'CZ', name : 'Czech Republic (+420)'},
        {id:'CI', name : 'Côte d\'Ivoire (+225)'},
        {id:'DK', name : 'Denmark (+45)'},
        {id:'DJ', name : 'Djibouti (+253)'},
        {id:'DM', name : 'Dominica (+1)'},
        {id:'DO', name : 'Dominican Republic (+1)'},
        {id:'EC', name : 'Ecuador (+593)'},
        {id:'EG', name : 'Egypt (+20)'},
        {id:'SV', name : 'El Salvador (+503)'},
        {id:'GQ', name : 'Equatorial Guinea (+240)'},
        {id:'ER', name : 'Eritrea (+291)'},
        {id:'EE', name : 'Estonia (+372)'},
        {id:'ET', name : 'Ethiopia (+251)'},
        {id:'FK', name : 'Falkland Islands (+500)'},
        {id:'FO', name : 'Faroe Islands (+298)'},
        {id:'FJ', name : 'Fiji (+679)'},
        {id:'FI', name : 'Finland (+358)'},
        {id:'FR', name : 'France (+33)'},
        {id:'GF', name : 'French Guiana (+594)'},
        {id:'PF', name : 'French Polynesia (+689)'},
        {id:'GA', name : 'Gabon (+241)'},
        {id:'GM', name : 'Gambia (+220)'},
        {id:'GE', name : 'Georgia (+995)'},
        {id:'DE', name : 'Germany (+49)'},
        {id:'GH', name : 'Ghana (+233)'},
        {id:'GI', name : 'Gibraltar (+350)'},
        {id:'GR', name : 'Greece (+30)'},
        {id:'GL', name : 'Greenland (+299)'},
        {id:'GD', name : 'Grenada (+1)'},
        {id:'GP', name : 'Guadeloupe (+590)'},
        {id:'GU', name : 'Guam (+1)'},
        {id:'GT', name : 'Guatemala (+502)'},
        {id:'GG', name : 'Guernsey (+44)'},
        {id:'GN', name : 'Guinea (+224)'},
        {id:'GW', name : 'Guinea-Bissau (+245)'},
        {id:'GY', name : 'Guyana (+592)'},
        {id:'HT', name : 'Haiti (+509)'},
        {id:'HN', name : 'Honduras (+504)'},
        {id:'HK', name : 'Hong Kong (+852)'},
        {id:'HU', name : 'Hungary (+36)'},
        {id:'IS', name : 'Iceland (+354)'},
        {id:'IN', name : 'India (+91)'},
        {id:'ID', name : 'Indonesia (+62)'},
        {id:'IR', name : 'Iran (+98)'},
        {id:'IQ', name : 'Iraq (+964)'},
        {id:'IE', name : 'Ireland (+353)'},
        {id:'IM', name : 'Isle Of Man (+44)'},
        {id:'IL', name : 'Israel (+972)'},
        {id:'IT', name : 'Italy (+39)'},
        {id:'JM', name : 'Jamaica (+1)'},
        {id:'JP', name : 'Japan (+81)'},
        {id:'JE', name : 'Jersey (+44)'},
        {id:'JO', name : 'Jordan (+962)'},
        {id:'KZ', name : 'Kazakhstan (+7)'},
        {id:'KE', name : 'Kenya (+254)'},
        {id:'KI', name : 'Kiribati (+686)'},
        {id:'KW', name : 'Kuwait (+965)'},
        {id:'KG', name : 'Kyrgyzstan (+996)'},
        {id:'LA', name : 'Laos (+856)'},
        {id:'LV', name : 'Latvia (+371)'},
        {id:'LB', name : 'Lebanon (+961)'},
        {id:'LS', name : 'Lesotho (+266)'},
        {id:'LR', name : 'Liberia (+231)'},
        {id:'LY', name : 'Libya (+218)'},
        {id:'LI', name : 'Liechtenstein (+423)'},
        {id:'LT', name : 'Lithuania (+370)'},
        {id:'LU', name : 'Luxembourg (+352)'},
        {id:'MO', name : 'Macao (+853)'},
        {id:'MK', name : 'Macedonia (+389)'},
        {id:'MG', name : 'Madagascar (+261)'},
        {id:'MW', name : 'Malawi (+265)'},
        {id:'MY', name : 'Malaysia (+60)'},
        {id:'MV', name : 'Maldives (+960)'},
        {id:'ML', name : 'Mali (+223)'},
        {id:'MT', name : 'Malta (+356)'},
        {id:'MH', name : 'Marshall Islands (+692)'},
        {id:'MQ', name : 'Martinique (+596)'},
        {id:'MR', name : 'Mauritania (+222)'},
        {id:'MU', name : 'Mauritius (+230)'},
        {id:'YT', name : 'Mayotte (+262)'},
        {id:'MX', name : 'Mexico (+52)'},
        {id:'FM', name : 'Micronesia (+691)'},
        {id:'MD', name : 'Moldova (+373)'},
        {id:'MC', name : 'Monaco (+377)'},
        {id:'MN', name : 'Mongolia (+976)'},
        {id:'ME', name : 'Montenegro (+382)'},
        {id:'MS', name : 'Montserrat (+1)'},
        {id:'MA', name : 'Morocco (+212)'},
        {id:'MZ', name : 'Mozambique (+258)'},
        {id:'MM', name : 'Myanmar (+95)'},
        {id:'NA', name : 'Namibia (+264)'},
        {id:'NR', name : 'Nauru (+674)'},
        {id:'NP', name : 'Nepal (+977)'},
        {id:'NL', name : 'Netherlands (+31)'},
        {id:'AN', name : 'Netherlands Antilles (+599)'},
        {id:'NC', name : 'New Caledonia (+687)'},
        {id:'NZ', name : 'New Zealand (+64)'},
        {id:'NI', name : 'Nicaragua (+505)'},
        {id:'NE', name : 'Niger (+227)'},
        {id:'NG', name : 'Nigeria (+234)'},
        {id:'NU', name : 'Niue (+683)'},
        {id:'NF', name : 'Norfolk Island (+672)'},
        {id:'KP', name : 'North Korea (+850)'},
        {id:'MP', name : 'Northern Mariana Islands (+1)'},
        {id:'NO', name : 'Norway (+47)'},
        {id:'OM', name : 'Oman (+968)'},
        {id:'PK', name : 'Pakistan (+92)'},
        {id:'PW', name : 'Palau (+680)'},
        {id:'PS', name : 'Palestine (+970)'},
        {id:'PA', name : 'Panama (+507)'},
        {id:'PG', name : 'Papua New Guinea (+675)'},
        {id:'PY', name : 'Paraguay (+595)'},
        {id:'PE', name : 'Peru (+51)'},
        {id:'PH', name : 'Philippines (+63)'},
        {id:'PL', name : 'Poland (+48)'},
        {id:'PT', name : 'Portugal (+351)'},
        {id:'PR', name : 'Puerto Rico (+1)'},
        {id:'QA', name : 'Qatar (+974)'},
        {id:'RE', name : 'Reunion (+262)'},
        {id:'RO', name : 'Romania (+40)'},
        {id:'RU', name : 'Russia (+7)'},
        {id:'RW', name : 'Rwanda (+250)'},
        {id:'BL', name : 'Saint Barthélemy (+590)'},
        {id:'SH', name : 'Saint Helena (+290)'},
        {id:'KN', name : 'Saint Kitts And Nevis (+1)'},
        {id:'LC', name : 'Saint Lucia (+1)'},
        {id:'MF', name : 'Saint Martin (+590)'},
        {id:'PM', name : 'Saint Pierre And Miquelon (+508)'},
        {id:'VC', name : 'Saint Vincent And The Grenadines (+1)'},
        {id:'WS', name : 'Samoa (+685)'},
        {id:'SM', name : 'San Marino (+378)'},
        {id:'ST', name : 'Sao Tome And Principe (+239)'},
        {id:'SA', name : 'Saudi Arabia (+966)'},
        {id:'SN', name : 'Senegal (+221)'},
        {id:'RS', name : 'Serbia (+381)'},
        {id:'SC', name : 'Seychelles (+248)'},
        {id:'SL', name : 'Sierra Leone (+232)'},
        {id:'SG', name : 'Singapore (+65)'},
        {id:'SX', name : 'Sint Maarten (Dutch part) (+1)'},
        {id:'SK', name : 'Slovakia (+421)'},
        {id:'SI', name : 'Slovenia (+386)'},
        {id:'SB', name : 'Solomon Islands (+677)'},
        {id:'SO', name : 'Somalia (+252)'},
        {id:'ZA', name : 'South Africa (+27)'},
        {id:'KR', name : 'South Korea (+82)'},
        {id:'ES', name : 'Spain (+34)'},
        {id:'LK', name : 'Sri Lanka (+94)'},
        {id:'SD', name : 'Sudan (+249)'},
        {id:'SR', name : 'Suriname (+597)'},
        {id:'SJ', name : 'Svalbard And Jan Mayen (+47)'},
        {id:'SZ', name : 'Swaziland (+268)'},
        {id:'SE', name : 'Sweden (+46)'},
        {id:'CH', name : 'Switzerland (+41)'},
        {id:'SY', name : 'Syria (+963)'},
        {id:'TW', name : 'Taiwan (+886)'},
        {id:'TJ', name : 'Tajikistan (+992)'},
        {id:'TZ', name : 'Tanzania (+255)'},
        {id:'TH', name : 'Thailand (+66)'},
        {id:'CD', name : 'The Democratic Republic Of Congo (+243)'},
        {id:'TL', name : 'Timor-Leste (+670)'},
        {id:'TG', name : 'Togo (+228)'},
        {id:'TK', name : 'Tokelau (+690)'},
        {id:'TO', name : 'Tonga (+676)'},
        {id:'TT', name : 'Trinidad and Tobago (+1)'},
        {id:'TN', name : 'Tunisia (+216)'},
        {id:'TR', name : 'Turkey (+90)'},
        {id:'TM', name : 'Turkmenistan (+993)'},
        {id:'TC', name : 'Turks And Caicos Islands (+1)'},
        {id:'TV', name : 'Tuvalu (+688)'},
        {id:'VI', name : 'U.S. Virgin Islands (+1)'},
        {id:'UG', name : 'Uganda (+256)'},
        {id:'UA', name : 'Ukraine (+380)'},
        {id:'AE', name : 'United Arab Emirates (+971)'},
        {id:'GB', name : 'United Kingdom (+44)'},
        {id:'US', name : 'United States (+1)'},
        {id:'UY', name : 'Uruguay (+598)'},
        {id:'UZ', name : 'Uzbekistan (+998)'},
        {id:'VU', name : 'Vanuatu (+678)'},
        {id:'VA', name : 'Vatican (+379)'},
        {id:'VE', name : 'Venezuela (+58)'},
        {id:'VN', name : 'Vietnam (+84)'},
        {id:'WF', name : 'Wallis And Futuna (+681)'},
        {id:'YE', name : 'Yemen (+967)'},
        {id:'ZM', name : 'Zambia (+260)'},
        {id:'ZW', name : 'Zimbabwe (+263)'},
        {id:'AX', name : 'Åland Islands (+358)'}
    ];
    return numbers;
}
