apiVersion: v1
kind: Service
metadata:
  name: greenhouseintegration-svc
  labels:
    app: greenhouseintegration
spec:
  type: NodePort
  ports:
   - port: 8090
  selector:
   app: greenhouseintegration
