apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-talent
  name: frontend-talent-svc
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: frontend-talent
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
