apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-website
  name: frontend-website-svc
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: frontend-website
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
