kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wildfly-storage-deployments-pv-claim
  labels:
    app: wildfly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
