apiVersion: v1
kind: Service
metadata:
  name: wfnet
  labels:
    app: wfnet
spec:
  ports:
  - name: "wfas"
    port: 8080
  - name: "wfconsole"
    port: 9990
  selector:
    app: wildfly
  type: NodePort
